spring:
  application:
    name: demo
  mvc:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_elite
    username: postgres
    password: Lemuel05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  error:
    # Per visualizzare tutti gli errori
    include-stacktrace: always

# http://localhost:8080/docente/nuovo